### PR TITLE
Bug/fix yarn build

### PR DESCRIPTION
**Pull request by briri**
- Rebuilt `package.json` file from the ground up
- Removed `popper.js` (we no longer use), `hogan.js` (don't see it used anywhere and it is no longer maintained), `puppeteer` (no reference to it anywhere), `rails-erb-loader` (we removed the use of this in a recent release), `react-scripts` (was causing a lot of vulnerability alerts for its dependencies and is only used to create new React apps), 
- Fixed some deprecated math calculations in the Rails sass files
- updated webpack config which was using deprecated babel plugins

Fixes for 502 errors #605.
- Added index to the `settings` table
- Performance improvements to the `registry_orgs_controller.rb`
- Performance improvements to the `answers_controller.rb`
- Performance improvements to the `plans_controller.rb` and `app/view/branded/plans/_download_form.html.erb`

### CODE REVIEW

**Comment by jupiter007** [comment]
The only comment I have is that I think the loaders for webpack typically go under "dependencies". But if it is working, then I guess it's not a problem.

**Review by jupiter007 — APPROVED** [review]

**Comment by briri** [comment]
thanks, I think you may be right. Rails' use of webpack is weird, and we moved to something called js-bundling when we upgraded to Rails 6 a year ago, so I'm not entirely sure what the relationship between the 3 is.  

I will move them back to dependencies if we see build errors or any visual errors in the the deployed code

**Comment by briri** [comment]
You were 💯 right @jupiter007. I moved those packages from `devDependencies` to normal `dependencies`. I also removed lingering references to the ERA loader in the web pack config.

This PR now also contains the few tweaks made to address the performance issues that were creating the 502 errors.

**Comment by briri** [comment]
am going to merge this one. It has been running now on the new AL2023 stage servers for several weeks. I am able to build the app and we haven't been receiving 502s.

**Pull request merged**
